name: teleportCommand
version: '1.0.0'
main: chipsonsky.randomTeleport.TeleportCommand
api-version: '1.16.5'
authors: [ chipsonsky ]
website: ru.chipsonsky
commands:
  rtp:
    usage: /rtp
    aliases: randomtp
    permission: Deluxe.Rtp
  spawn:
    usage: /spawn
    permission: Deluxe.Spawn
    aliases: hub
  deluxe:
    usage: /deluxe <args>
    permission: Deluxe.Admin
