#Телепортации
#Тесты на версии 1.21.1
#Команды плагина:
# /spawn - телепортирует на спавн по указанным в конфиге координатам
# /rtp - телепортирует на рандомные координаты, укажите в конфиге границы
# /deluxe <arg> - админские команды с настройками в игре
# Телеграм разработчика: @DeluxePlugin
# Заказать плагин: @chipsonsky
# Это первая версия плагина

#Координаты для телепортации
min_minus: -1500
max_minus: -300
min: 300
max: 1500
#Секунды
#Время перед телепортацией
teleport_timer: 5
#Задержка для телепортации
cooldown: 60
#Время эффекта слепоты при телепортации(в секундах)
effect_time: 5

#Надпись над босс баром
boss_bar_title: "До телепорта осталось %time%"
#Цвет боссБара, доступны все цвета радуги
boss_bat_color: RED

#Координаты спавна
spawnX: 0
spawnY: 88
spawnZ: 0
#Задержка для телепортации
cooldownS: 60
#Время телпортации
spawn_teleport_timer: 5

#Настройки чата
chat:
  #Префикс перед командными сообщениями
  prefix: "&x&6&9&3&D&F&F&lD&x&6&E&3&8&F&7&le&x&7&3&3&4&E&F&ll&x&7&8&2&F&E&7&lu&x&7&D&2&A&D&F&lx&x&8&2&2&6&D&7&le&x&8&7&2&1&C&F&l:&r "

